import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
    slider: [
        'intro',
        {
            type: 'category',
            label: '연혁',
            link: {type: "doc", id: "histories",},
            items: [{type: 'autogenerated', dirName: 'histories'}],
        },
        {
            type: 'category',
            label: '활동',
            link: {type: 'generated-index', slug: 'activities'},
            items: [{type: 'autogenerated', dirName: 'activities'},],
        },
        {
            type: 'category',
            label: '회원',
            link: {type: 'generated-index', slug: 'members'},
            items: [{type: 'autogenerated', dirName: 'members'}],
        },
        {
            type: 'category',
            label: '졸업회원',
            link: {type: 'generated-index', slug: 'graduates'},
            items: [{type: 'autogenerated', dirName: 'graduates'}],
        },
        'recruit',
        'contact',
    ],
};

export default sidebars;
