import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
    slider: [
        'intro',
        'history',
        {
            type: 'category',
            label: '활동',
            link: {
                type: 'doc',
                id: 'activities',
            },
            items: [{type: 'autogenerated', dirName: 'activities'}],
        },
        {
            type: 'category',
            label: '회원',
            link: {
                type: 'doc',
                id: 'members',
            },
            items: [{type: 'autogenerated', dirName: 'members'}],
        },
        'recruit',
        'contact',
    ],
};

export default sidebars;
